module.exports = {
    "date": "2017-09-16",
    "time_of_day": "21:53",
    "request_time": "2017-09-16T21:53:15+01:00",
    "station_name": "Milton Keynes Central",
    "station_code": "mkc",
    "departures": {
        "all": [{
                "mode": "train",
                "service": "22112001",
                "train_uid": "P51778",
                "platform": "1",
                "operator": "VT",
                "operator_name": "Virgin Trains",
                "aimed_departure_time": "21:52",
                "aimed_arrival_time": "21:51",
                "aimed_pass_time": null,
                "origin_name": "Glasgow Central",
                "source": "Network Rail",
                "destination_name": "London Euston",
                "category": "XX",
                "service_timetable": {
                    "id": "http://transportapi.com/v3/uk/train/service/train_uid:P51778/2017-09-16/timetable.json?app_id=8c606c32&app_key=9d67b288f576384058b136a5801637f3&live=true"
                },
                "status": "LATE",
                "expected_arrival_time": "21:58",
                "expected_departure_time": "21:59",
                "best_arrival_estimate_mins": 4,
                "best_departure_estimate_mins": 5
            },
            {
                "mode": "train",
                "service": "22114001",
                "train_uid": "P52464",
                "platform": "1",
                "operator": "VT",
                "operator_name": "Virgin Trains",
                "aimed_departure_time": "22:05",
                "aimed_arrival_time": "22:04",
                "aimed_pass_time": null,
                "origin_name": "Edinburgh Waverley",
                "source": "Network Rail",
                "destination_name": "London Euston",
                "category": "XX",
                "service_timetable": {
                    "id": "http://transportapi.com/v3/uk/train/service/train_uid:P52464/2017-09-16/timetable.json?app_id=8c606c32&app_key=9d67b288f576384058b136a5801637f3&live=true"
                },
                "status": "LATE",
                "expected_arrival_time": "22:05",
                "expected_departure_time": "22:06",
                "best_arrival_estimate_mins": 11,
                "best_departure_estimate_mins": 12
            },
            {
                "mode": "train",
                "service": "22209000",
                "train_uid": "P46542",
                "platform": "3",
                "operator": "LM",
                "operator_name": "London Midland",
                "aimed_departure_time": "22:06",
                "aimed_arrival_time": "22:05",
                "aimed_pass_time": null,
                "origin_name": "London Euston",
                "source": "Network Rail",
                "destination_name": "Northampton",
                "category": "OO",
                "service_timetable": {
                    "id": "http://transportapi.com/v3/uk/train/service/train_uid:P46542/2017-09-16/timetable.json?app_id=8c606c32&app_key=9d67b288f576384058b136a5801637f3&live=true"
                },
                "status": "NO REPORT",
                "expected_arrival_time": "22:05",
                "expected_departure_time": "22:06",
                "best_arrival_estimate_mins": 11,
                "best_departure_estimate_mins": 12
            },
            {
                "mode": "train",
                "service": "22108001",
                "train_uid": "P51418",
                "platform": "1",
                "operator": "VT",
                "operator_name": "Virgin Trains",
                "aimed_departure_time": "22:11",
                "aimed_arrival_time": "22:10",
                "aimed_pass_time": null,
                "origin_name": "Manchester Piccadilly",
                "source": "Network Rail",
                "destination_name": "London Euston",
                "category": "XX",
                "service_timetable": {
                    "id": "http://transportapi.com/v3/uk/train/service/train_uid:P51418/2017-09-16/timetable.json?app_id=8c606c32&app_key=9d67b288f576384058b136a5801637f3&live=true"
                },
                "status": "ON TIME",
                "expected_arrival_time": "22:10",
                "expected_departure_time": "22:11",
                "best_arrival_estimate_mins": 16,
                "best_departure_estimate_mins": 17
            },
            {
                "mode": "train",
                "service": "12259320",
                "train_uid": "P47993",
                "platform": "2",
                "operator": "LM",
                "operator_name": "London Midland",
                "aimed_departure_time": "22:21",
                "aimed_arrival_time": "22:20",
                "aimed_pass_time": null,
                "origin_name": "Birmingham New Street",
                "source": "Network Rail",
                "destination_name": "London Euston",
                "category": "OO",
                "service_timetable": {
                    "id": "http://transportapi.com/v3/uk/train/service/train_uid:P47993/2017-09-16/timetable.json?app_id=8c606c32&app_key=9d67b288f576384058b136a5801637f3&live=true"
                },
                "status": "LATE",
                "expected_arrival_time": "22:24",
                "expected_departure_time": "22:25",
                "best_arrival_estimate_mins": 30,
                "best_departure_estimate_mins": 31
            },
            {
                "mode": "train",
                "service": "22209000",
                "train_uid": "P48013",
                "platform": "3",
                "operator": "LM",
                "operator_name": "London Midland",
                "aimed_departure_time": "22:24",
                "aimed_arrival_time": "22:23",
                "aimed_pass_time": null,
                "origin_name": "London Euston",
                "source": "Network Rail",
                "destination_name": "Birmingham New Street",
                "category": "OO",
                "service_timetable": {
                    "id": "http://transportapi.com/v3/uk/train/service/train_uid:P48013/2017-09-16/timetable.json?app_id=8c606c32&app_key=9d67b288f576384058b136a5801637f3&live=true"
                },
                "status": "ON TIME",
                "expected_arrival_time": "22:23",
                "expected_departure_time": "22:24",
                "best_arrival_estimate_mins": 29,
                "best_departure_estimate_mins": 30
            },
            {
                "mode": "train",
                "service": "22100001",
                "train_uid": "P51487",
                "platform": "2",
                "operator": "VT",
                "operator_name": "Virgin Trains",
                "aimed_departure_time": "22:26",
                "aimed_arrival_time": "22:24",
                "aimed_pass_time": null,
                "origin_name": "Wolverhampton",
                "source": "Network Rail",
                "destination_name": "London Euston",
                "category": "XX",
                "service_timetable": {
                    "id": "http://transportapi.com/v3/uk/train/service/train_uid:P51487/2017-09-16/timetable.json?app_id=8c606c32&app_key=9d67b288f576384058b136a5801637f3&live=true"
                },
                "status": "LATE",
                "expected_arrival_time": "22:36",
                "expected_departure_time": "22:38",
                "best_arrival_estimate_mins": 42,
                "best_departure_estimate_mins": 44
            },
            {
                "mode": "train",
                "service": "22100001",
                "train_uid": "P52405",
                "platform": "3",
                "operator": "VT",
                "operator_name": "Virgin Trains",
                "aimed_departure_time": "22:30",
                "aimed_arrival_time": "22:29",
                "aimed_pass_time": null,
                "origin_name": "London Euston",
                "source": "Network Rail",
                "destination_name": "Wolverhampton",
                "category": "XX",
                "service_timetable": {
                    "id": "http://transportapi.com/v3/uk/train/service/train_uid:P52405/2017-09-16/timetable.json?app_id=8c606c32&app_key=9d67b288f576384058b136a5801637f3&live=true"
                },
                "status": "EARLY",
                "expected_arrival_time": "22:29",
                "expected_departure_time": "22:30",
                "best_arrival_estimate_mins": 35,
                "best_departure_estimate_mins": 36
            },
            {
                "mode": "train",
                "service": "12259320",
                "train_uid": "P47998",
                "platform": "1",
                "operator": "LM",
                "operator_name": "London Midland",
                "aimed_departure_time": "22:59",
                "aimed_arrival_time": "22:59",
                "aimed_pass_time": null,
                "origin_name": "Birmingham New Street",
                "source": "Network Rail",
                "destination_name": "London Euston",
                "category": "OO",
                "service_timetable": {
                    "id": "http://transportapi.com/v3/uk/train/service/train_uid:P47998/2017-09-16/timetable.json?app_id=8c606c32&app_key=9d67b288f576384058b136a5801637f3&live=true"
                },
                "status": "LATE",
                "expected_arrival_time": "23:00",
                "expected_departure_time": "23:00",
                "best_arrival_estimate_mins": 66,
                "best_departure_estimate_mins": 66
            },
            {
                "mode": "train",
                "service": "22209000",
                "train_uid": "P46551",
                "platform": "3",
                "operator": "LM",
                "operator_name": "London Midland",
                "aimed_departure_time": "23:03",
                "aimed_arrival_time": "23:02",
                "aimed_pass_time": null,
                "origin_name": "London Euston",
                "source": "Network Rail",
                "destination_name": "Northampton",
                "category": "OO",
                "service_timetable": {
                    "id": "http://transportapi.com/v3/uk/train/service/train_uid:P46551/2017-09-16/timetable.json?app_id=8c606c32&app_key=9d67b288f576384058b136a5801637f3&live=true"
                },
                "status": "CANCELLED",
                "expected_arrival_time": null,
                "expected_departure_time": null,
                "best_arrival_estimate_mins": null,
                "best_departure_estimate_mins": null
            },
            {
                "mode": "train",
                "service": "22209000",
                "train_uid": "P46555",
                "platform": "3",
                "operator": "LM",
                "operator_name": "London Midland",
                "aimed_departure_time": "23:31",
                "aimed_arrival_time": "23:31",
                "aimed_pass_time": null,
                "origin_name": "London Euston",
                "source": "Network Rail",
                "destination_name": "Northampton",
                "category": "OO",
                "service_timetable": {
                    "id": "http://transportapi.com/v3/uk/train/service/train_uid:P46555/2017-09-16/timetable.json?app_id=8c606c32&app_key=9d67b288f576384058b136a5801637f3&live=true"
                },
                "status": "ON TIME",
                "expected_arrival_time": "23:31",
                "expected_departure_time": "23:31",
                "best_arrival_estimate_mins": 97,
                "best_departure_estimate_mins": 97
            },
            {
                "mode": "train",
                "service": "12259320",
                "train_uid": "P47965",
                "platform": "1",
                "operator": "LM",
                "operator_name": "London Midland",
                "aimed_departure_time": "23:46",
                "aimed_arrival_time": "23:46",
                "aimed_pass_time": null,
                "origin_name": "Birmingham New Street",
                "source": "Network Rail",
                "destination_name": "London Euston",
                "category": "OO",
                "service_timetable": {
                    "id": "http://transportapi.com/v3/uk/train/service/train_uid:P47965/2017-09-16/timetable.json?app_id=8c606c32&app_key=9d67b288f576384058b136a5801637f3&live=true"
                },
                "status": "ON TIME",
                "expected_arrival_time": "23:46",
                "expected_departure_time": "23:46",
                "best_arrival_estimate_mins": 112,
                "best_departure_estimate_mins": 112
            }
        ]
    }
}